from flask_wtf import FlaskForm
from wtforms import IntegerField, StringField, SubmitField, BooleanField, PasswordField, SelectField
from wtforms.validators import DataRequired, Email, EqualTo, Length, Optional

from app import db
from app.models import UsersInfo,Quests, HintsSolutions, PlayerTracker, CompletedQuests

class RegistrationForm(FlaskForm):
    name = StringField('First Name', validators=[DataRequired()])
    surname = StringField('Last Name', validators=[DataRequired()])
    email = StringField('Email Address', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password')])
    city = StringField('City', validators=[DataRequired()])
    suburb = StringField('Suburb', validators=[DataRequired()])
    points = IntegerField('Points')
    quests_completed = IntegerField('Quests Completed')
    submit = SubmitField('Sign Up')

class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Sign In')
    register = SubmitField('Register')

class QuestForm(FlaskForm):
    q_title = StringField('Quest Title', validators=[DataRequired(), Length(max=200)])
    q_duration = SelectField('Duration', choices=[('0 - 10min', '0 - 10 minutes'),
                                                ('10 - 30min', '10 - 30 minutes'),
                                                ('30 - 60min', '30 - 60 minutes'),
                                                ('1 - 3 hours', '1 - 3 hours'),
                                                ('3+ hours', '3+ hours')],
                            validators=[DataRequired()])
    difficulty = SelectField('Difficulty', choices=[('Easy', 'Easy'),
                                                    ('Medium', 'Medium'),
                                                    ('Hard', 'Hard'),
                                                    ('Boss', 'Boss')],
                            validators=[DataRequired()])
    quest_suburb = SelectField('Suburb', choices = [
        ('Across Multiple Suburbs', 'Across Multiple Suburbs'),
        ('Alexander Heights', 'Alexander Heights'),
        ('Alfred Cove', 'Alfred Cove'),
        ('Alkimos', 'Alkimos'),
        ('Anketell', 'Anketell'),
        ('Applecross', 'Applecross'),
        ('Ardross', 'Ardross'),
        ('Armadale', 'Armadale'),
        ('Ascot', 'Ascot'),
        ('Ashby', 'Ashby'),
        ('Ashfield', 'Ashfield'),
        ('Attadale', 'Attadale'),
        ('Atwell', 'Atwell'),
        ('Aubin Grove', 'Aubin Grove'),
        ('Aveley', 'Aveley'),
        ('Bailup', 'Bailup'),
        ('Balcatta', 'Balcatta'),
        ('Baldivis', 'Baldivis'),
        ('Balga', 'Balga'),
        ('Ballajura', 'Ballajura'),
        ('Banjup', 'Banjup'),
        ('Banksia Grove', 'Banksia Grove'),
        ('Baskerville', 'Baskerville'),
        ('Bassendean', 'Bassendean'),
        ('Bateman', 'Bateman'),
        ('Bayswater', 'Bayswater'),
        ('Beaconsfield', 'Beaconsfield'),
        ('Beckenham', 'Beckenham'),
        ('Bedford', 'Bedford'),
        ('Bedfordale', 'Bedfordale'),
        ('Beechboro', 'Beechboro'),
        ('Beechina', 'Beechina'),
        ('Beeliar', 'Beeliar'),
        ('Beldon', 'Beldon'),
        ('Belhus', 'Belhus'),
        ('Bellevue', 'Bellevue'),
        ('Belmont', 'Belmont'),
        ('Bennett Springs', 'Bennett Springs'),
        ('Bentley', 'Bentley'),
        ('Bertram', 'Bertram'),
        ('Bibra Lake', 'Bibra Lake'),
        ('Bickley', 'Bickley'),
        ('Bicton', 'Bicton'),
        ('Booragoon', 'Booragoon'),
        ('Boya', 'Boya'),
        ('Brabham', 'Brabham'),
        ('Brentwood', 'Brentwood'),
        ('Brigadoon', 'Brigadoon'),
        ('Brookdale', 'Brookdale'),
        ('Bull Creek', 'Bull Creek'),
        ('Bullsbrook', 'Bullsbrook'),
        ('Burns Beach', 'Burns Beach'),
        ('Burswood', 'Burswood'),
        ('Butler', 'Butler'),
        ('Byford', 'Byford'),
        ('Calista', 'Calista'),
        ('Camillo', 'Camillo'),
        ('Canning Vale', 'Canning Vale'),
        ('Cannington', 'Cannington'),
        ('Carabooda', 'Carabooda'),
        ('Cardup', 'Cardup'),
        ('Carine', 'Carine'),
        ('Carlisle', 'Carlisle'),
        ('Carmel', 'Carmel'),
        ('Carramar', 'Carramar'),
        ('Casuarina', 'Casuarina'),
        ('Caversham', 'Caversham'),
        ('Champion Lakes', 'Champion Lakes'),
        ('Chidlow', 'Chidlow'),
        ('Churchlands', 'Churchlands'),
        ('City Beach', 'City Beach'),
        ('Claremont', 'Claremont'),
        ('Clarkson', 'Clarkson'),
        ('Clifton Park', 'Clifton Park'),
        ('Cloverdale', 'Cloverdale'),
        ('Cockburn Central', 'Cockburn Central'),
        ('Como', 'Como'),
        ('Connolly', 'Connolly'),
        ('Coogee', 'Coogee'),
        ('Coolbellup', 'Coolbellup'),
        ('Coolbinia', 'Coolbinia'),
        ('Cooloongup', 'Cooloongup'),
        ('Cottesloe', 'Cottesloe'),
        ('Craigie', 'Craigie'),
        ('Crawley', 'Crawley'),
        ('Cullacabardee', 'Cullacabardee'),
        ('Currambine', 'Currambine'),
        ('Daglish', 'Daglish'),
        ('Dalkeith', 'Dalkeith'),
        ('Darch', 'Darch'),
        ('Darling Downs', 'Darling Downs'),
        ('Darlington', 'Darlington'),
        ('Dayton', 'Dayton'),
        ('Dianella', 'Dianella'),
        ('Doubleview', 'Doubleview'),
        ('Duncraig', 'Duncraig'),
        ('East Cannington', 'East Cannington'),
        ('East Fremantle', 'East Fremantle'),
        ('East Perth', 'East Perth'),
        ('East Rockingham', 'East Rockingham'),
        ('East Victoria Park', 'East Victoria Park'),
        ('Eden Hill', 'Eden Hill'),
        ('Edgewater', 'Edgewater'),
        ('Eglinton', 'Eglinton'),
        ('Ellenbrook', 'Ellenbrook'),
        ('Embleton', 'Embleton'),
        ('Ferndale', 'Ferndale'),
        ('Floreat', 'Floreat'),
        ('Forrestdale', 'Forrestdale'),
        ('Forrestfield', 'Forrestfield'),
        ('Fremantle', 'Fremantle'),
        ('Garden Island', 'Garden Island'),
        ('Gidgegannup', 'Gidgegannup'),
        ('Girrawheen', 'Girrawheen'),
        ('Glen Forrest', 'Glen Forrest'),
        ('Glendalough', 'Glendalough'),
        ('Gnangara', 'Gnangara'),
        ('Golden Bay', 'Golden Bay'),
        ('Gooseberry Hill', 'Gooseberry Hill'),
        ('Gosnells', 'Gosnells'),
        ('Greenmount', 'Greenmount'),
        ('Greenwood', 'Greenwood'),
        ('Guildford', 'Guildford'),
        ('Gwelup', 'Gwelup'),
        ('Hacketts Gully', 'Hacketts Gully'),
        ('Hamersley', 'Hamersley'),
        ('Hamilton Hill', 'Hamilton Hill'),
        ('Hammond Park', 'Hammond Park'),
        ('Harrisdale', 'Harrisdale'),
        ('Haynes', 'Haynes'),
        ('Hazelmere', 'Hazelmere'),
        ('Heathridge', 'Heathridge'),
        ('Helena Valley', 'Helena Valley'),
        ('Henderson', 'Henderson'),
        ('Henley Brook', 'Henley Brook'),
        ('Herdsmans Cove', 'Herdsmans Cove'),
        ('Herne Hill', 'Herne Hill'),
        ('High Wycombe', 'High Wycombe'),
        ('Highgate', 'Highgate'),
        ('Hillarys', 'Hillarys'),
        ('Hillman', 'Hillman'),
        ('Hilton', 'Hilton'),
        ('Hocking', 'Hocking'),
        ('Hovea', 'Hovea'),
        ('Huntingdale', 'Huntingdale'),
        ('Iluka', 'Iluka'),
        ('Inglewood', 'Inglewood'),
        ('Innaloo', 'Innaloo'),
        ('Jandakot', 'Jandakot'),
        ('Jane Brook', 'Jane Brook'),
        ('Jarrahdale', 'Jarrahdale'),
        ('Jindalee', 'Jindalee'),
        ('Jolimont', 'Jolimont'),
        ('Joondalup', 'Joondalup'),
        ('Joondanna', 'Joondanna'),
        ('Kalamunda', 'Kalamunda'),
        ('Kallaroo', 'Kallaroo'),
        ('Karawara', 'Karawara'),
        ('Kardinya', 'Kardinya'),
        ('Karnup', 'Karnup'),
        ('Karragullen', 'Karragullen'),
        ('Karrakatta', 'Karrakatta'),
        ('Karrakup', 'Karrakup'),
        ('Karrinyup', 'Karrinyup'),
        ('Kelmscott', 'Kelmscott'),
        ('Kensington', 'Kensington'),
        ('Kenwick', 'Kenwick'),
        ('Keralup', 'Keralup'),
        ('Kewdale', 'Kewdale'),
        ('Keysbrook', 'Keysbrook'),
        ('Kiara', 'Kiara'),
        ('Kingsley', 'Kingsley'),
        ('Kinross', 'Kinross'),
        ('Koongamia', 'Koongamia'),
        ('Kwinana Beach', 'Kwinana Beach'),
        ('Kwinana Town Centre', 'Kwinana Town Centre'),
        ('Landsdale', 'Landsdale'),
        ('Langford', 'Langford'),
        ('Lathlain', 'Lathlain'),
        ('Leda', 'Leda'),
        ('Leederville', 'Leederville'),
        ('Leeming', 'Leeming'),
        ('Lesmurdie', 'Lesmurdie'),
        ('Lexia', 'Lexia'),
        ('Lockridge', 'Lockridge'),
        ('Lynwood', 'Lynwood'),
        ('Maddington', 'Maddington'),
        ('Madeley', 'Madeley'),
        ('Mahogany Creek', 'Mahogany Creek'),
        ('Maida Vale', 'Maida Vale'),
        ('Malaga', 'Malaga'),
        ('Mandogalup', 'Mandogalup'),
        ('Manning', 'Manning'),
        ('Marangaroo', 'Marangaroo'),
        ('Mardella', 'Mardella'),
        ('Mariginiup', 'Mariginiup'),
        ('Marmion', 'Marmion'),
        ('Martin', 'Martin'),
        ('Maylands', 'Maylands'),
        ('Medina', 'Medina'),
        ('Melaleuca', 'Melaleuca'),
        ('Melville', 'Melville'),
        ('Menora', 'Menora'),
        ('Merriwa', 'Merriwa'),
        ('Middle Swan', 'Middle Swan'),
        ('Midland', 'Midland'),
        ('Midvale', 'Midvale'),
        ('Millars Well', 'Millars Well'),
        ('Millendon', 'Millendon'),
        ('Mindarie', 'Mindarie'),
        ('Mirrabooka', 'Mirrabooka'),
        ('Morley', 'Morley'),
        ('Mosman Park', 'Mosman Park'),
        ('Mount Claremont', 'Mount Claremont'),
        ('Mount Hawthorn', 'Mount Hawthorn'),
        ('Mount Helena', 'Mount Helena'),
        ('Mount Lawley', 'Mount Lawley'),
        ('Mount Nasura', 'Mount Nasura'),
        ('Mount Pleasant', 'Mount Pleasant'),
        ('Mount Richon', 'Mount Richon'),
        ('Muckenburra', 'Muckenburra'),
        ('Mullaloo', 'Mullaloo'),
        ('Mundaring', 'Mundaring'),
        ('Mundijong', 'Mundijong'),
        ('Munster', 'Munster'),
        ('Murdoch', 'Murdoch'),
        ('Myaree', 'Myaree'),
        ('Nedlands', 'Nedlands'),
        ('Neerabup', 'Neerabup'),
        ('Nollamara', 'Nollamara'),
        ('Noranda', 'Noranda'),
        ('North Beach', 'North Beach'),
        ('North Coogee', 'North Coogee'),
        ('North Fremantle', 'North Fremantle'),
        ('North Lake', 'North Lake'),
        ('North Perth', 'North Perth'),
        ('North Yunderup', 'North Yunderup'),
        ('Nowergup', 'Nowergup'),
        ('Oakford', 'Oakford'),
        ('Ocean Reef', 'Ocean Reef'),
        ('Oldbury', 'Oldbury'),
        ('Orange Grove', 'Orange Grove'),
        ('Orelia', 'Orelia'),
        ('Osborne Park', 'Osborne Park'),
        ('Padbury', 'Padbury'),
        ('Palmyra', 'Palmyra'),
        ('Parkerville', 'Parkerville'),
        ('Parkwood', 'Parkwood'),
        ('Parmelia', 'Parmelia'),
        ('Paulls Valley', 'Paulls Valley'),
        ('Pearsall', 'Pearsall'),
        ('Peppermint Grove', 'Peppermint Grove'),
        ('Peron', 'Peron'),
        ('Perth', 'Perth'),
        ('Piara Waters', 'Piara Waters'),
        ('Pickering Brook', 'Pickering Brook'),
        ('Piesse Brook', 'Piesse Brook'),
        ('Pinjar', 'Pinjar'),
        ('Point Samson', 'Point Samson'),
        ('Port Kennedy', 'Port Kennedy'),
        ('Postans', 'Postans'),
        ('Prevelly', 'Prevelly'),
        ('Quinns Rocks', 'Quinns Rocks'),
        ('Red Hill', 'Red Hill'),
        ('Redcliffe', 'Redcliffe'),
        ('Ridgewood', 'Ridgewood'),
        ('Riverton', 'Riverton'),
        ('Rockingham', 'Rockingham'),
        ('Roleystone', 'Roleystone'),
        ('Rossmoyne', 'Rossmoyne'),
        ('Safety Bay', 'Safety Bay'),
        ('Salter Point', 'Salter Point'),
        ('Samson', 'Samson'),
        ('Sawyers Valley', 'Sawyers Valley'),
        ('Scarborough', 'Scarborough'),
        ('Secret Harbour', 'Secret Harbour'),
        ('Seville Grove', 'Seville Grove'),
        ('Shelley', 'Shelley'),
        ('Shenton Park', 'Shenton Park'),
        ('Shoalwater', 'Shoalwater'),
        ('Sinagra', 'Sinagra'),
        ('Singleton', 'Singleton'),
        ('Sorrento', 'Sorrento'),
        ('South Fremantle', 'South Fremantle'),
        ('South Guildford', 'South Guildford'),
        ('South Lake', 'South Lake'),
        ('South Perth', 'South Perth'),
        ('Southern River', 'Southern River'),
        ('Spearwood', 'Spearwood'),
        ('St James', 'St James'),
        ('Stirling', 'Stirling'),
        ('Straffon', 'Straffon'),
        ('Stratton', 'Stratton'),
        ('Subiaco', 'Subiaco'),
        ('Success', 'Success'),
        ('Swan View', 'Swan View'),
        ('Swanbourne', 'Swanbourne'),
        ('Tapping', 'Tapping'),
        ('The Lakes', 'The Lakes'),
        ('The Spectacles', 'The Spectacles'),
        ('The Vines', 'The Vines'),
        ('Thornlie', 'Thornlie'),
        ('Trigg', 'Trigg'),
        ('Tuart Hill', 'Tuart Hill'),
        ('Two Rocks', 'Two Rocks'),
        ('Upper Swan', 'Upper Swan'),
        ('Victoria Park', 'Victoria Park'),
        ('Viveash', 'Viveash'),
        ('Waikiki', 'Waikiki'),
        ('Walliston', 'Walliston'),
        ('Wandi', 'Wandi'),
        ('Wangara', 'Wangara'),
        ('Wanneroo', 'Wanneroo'),
        ('Warnbro', 'Warnbro'),
        ('Warwick', 'Warwick'),
        ('Waterford', 'Waterford'),
        ('Watermans Bay', 'Watermans Bay'),
        ('Wattle Grove', 'Wattle Grove'),
        ('Wattleup', 'Wattleup'),
        ('Wellard', 'Wellard'),
        ('Welshpool', 'Welshpool'),
        ('Wembley', 'Wembley'),
        ('Wembley Downs', 'Wembley Downs'),
        ('West Leederville', 'West Leederville'),
        ('West Perth', 'West Perth'),
        ('West Swan', 'West Swan'),
        ('Westminster', 'Westminster'),
        ('Whitby', 'Whitby'),
        ('White Gum Valley', 'White Gum Valley'),
        ('Whiteman', 'Whiteman'),
        ('Willagee', 'Willagee'),
        ('Willetton', 'Willetton'),
        ('Wilson', 'Wilson'),
        ('Winthrop', 'Winthrop'),
        ('Woodbridge', 'Woodbridge'),
        ('Woodlands', 'Woodlands'),
        ('Woodvale', 'Woodvale'),
        ('Wooroloo', 'Wooroloo'),
        ('Wungong', 'Wungong'),
        ('Yanchep', 'Yanchep'),
        ('Yangebup', 'Yangebup'),
        ('Yokine', 'Yokine')], 
        validators=[DataRequired()])
    hint_1 = StringField('Hint 1', validators=[DataRequired(), Length(max=300)])
    solution_1 = StringField('Solution 1', validators=[DataRequired(), Length(max=150)])
    hint_2 = StringField('Hint 2', validators=[DataRequired(), Length(max=300)])
    solution_2 = StringField('Solution 2', validators=[DataRequired(), Length(max=150)])
    hint_3 = StringField('Hint 3', validators=[DataRequired(), Length(max=300)])
    solution_3 = StringField('Solution 3', validators=[DataRequired(), Length(max=150)])
    hint_4 = StringField('Hint 4', validators=[DataRequired(), Length(max=300)])
    solution_4 = StringField('Solution 4', validators=[DataRequired(), Length(max=150)])
    hint_5 = StringField('Hint 5', validators=[DataRequired(), Length(max=300)])
    solution_5 = StringField('Solution 5', validators=[DataRequired(), Length(max=150)])
    submit = SubmitField('Submit')
